### ISSUE TITLE
Typos in the script

### ISSUE THREAD

**Issue by msuhanov** [op7ic/unix_collector#5]
Hello.

There is a missing space here:
https://github.com/op7ic/unix_collector/blob/b6900433dced242ab9858b059aa56a4604469f0a/unix_collector.sh#L827

This:
`--exclude-from$OUTPUT_DIR`

This creates problems when collecting files from `/root/` (when no `rsync` is found).

**Comment by msuhanov** [comment]
https://github.com/op7ic/unix_collector/blob/b6900433dced242ab9858b059aa56a4604469f0a/unix_collector.sh#L987
https://github.com/op7ic/unix_collector/blob/b6900433dced242ab9858b059aa56a4604469f0a/unix_collector.sh#L1002

The `-size` argument isn't needed here. Actually, it forces the script to skip files to be collected.

**Comment by msuhanov** [comment]
Also:
https://github.com/op7ic/unix_collector/blob/b6900433dced242ab9858b059aa56a4604469f0a/unix_collector.sh#L492
No output redirection here...

**Comment by msuhanov** [comment]
Also, the path is missing here (only the file name is given):
https://github.com/op7ic/unix_collector/blob/b6900433dced242ab9858b059aa56a4604469f0a/unix_collector.sh#L458

(And in other places too...)

**Comment by op7ic** [comment]
Hi @msuhanov ,

Great reports - thank you very much for taking time to report this !

I fixed the following:

https://github.com/op7ic/unix_collector/issues/5#issue-1929933439
https://github.com/op7ic/unix_collector/issues/5#issuecomment-1750599076
https://github.com/op7ic/unix_collector/issues/5#issuecomment-1755681097
https://github.com/op7ic/unix_collector/issues/5#issuecomment-1755702554

This one is on purpose to limit collection up to certain size (500mb).  
https://github.com/op7ic/unix_collector/issues/5#issuecomment-1755514061

**Comment by msuhanov** [comment]
> This one is on purpose to limit collection up to certain size (500mb).

I think that it works in another direction.

`TAR_MAX_FILESIZE=+500M`
`find / -size $TAR_MAX_FILESIZE -type f`

From `man find`:
```
       A numeric argument n can be specified to  tests  (like  -amin,  -mtime,
       -gid, -inum, -links, -size, -uid and -used) as

       +n     for greater than n,
```

So, it searches for files larger than 500M.

**Comment by op7ic** [comment]
@msuhanov  you arfe right- changed it from +500 to -500 which should grab files that are up to 500mb.

**Comment by op7ic** [comment]
changes complete

**Comment by msuhanov** [comment]
Not sure if such a change would be okay here:

https://github.com/op7ic/unix_collector/blob/7e0bec3a714ebe9dbc3a8039392b339185564905/unix_collector.sh#L846
