### ISSUE TITLE
Inconsistent usage of tar

### ISSUE THREAD

**Issue by msuhanov** [op7ic/unix_collector#6]
Hello.

It seems that `tar` is called with wrong arguments in the script.

1. There is no `--exclude-from` argument in Solaris.
https://github.com/op7ic/unix_collector/blob/b6900433dced242ab9858b059aa56a4604469f0a/unix_collector.sh#L777

2. In macOS, the `--exclude-from` argument must be given before the path (to be archived).
https://github.com/op7ic/unix_collector/blob/b6900433dced242ab9858b059aa56a4604469f0a/unix_collector.sh#L811

3. In GNU/Linux, things are more complicated with the `--exclude-from` argument.
https://github.com/op7ic/unix_collector/blob/b6900433dced242ab9858b059aa56a4604469f0a/unix_collector.sh#L826
See: https://stackoverflow.com/a/56350393

**Comment by op7ic** [comment]
Hi @msuhanov, thank you for another great report. I started to fix this. Great observation.

**Comment by op7ic** [comment]
@msuhanov  added migration and corrected order of the tar parameters. Closing this ticket now.
